-- Verificar estructura de pNetUsuarioPassword
USE PP;
GO

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'pNetUsuarioPassword'
ORDER BY ORDINAL_POSITION;
