-- =============================================
-- DEPRECADO: Este script ya no se necesita.
-- La tabla ProvFacturas ya existe en la base PP con la estructura del ERP.
-- Las columnas adicionales se agregan via sql/add_blob_columns.sql
-- Fecha de deprecacion: 2026-02-11
-- =============================================
